import type { DemoRecord } from "../api/seed.ts";
export type GrowthRule={id:string;version:number;kind:"promo"|"bonus"|"referral";zone:string;budgetOre:number;rewardOre:number;cap:number;targetTrips:number;stacks:boolean;enabled:boolean;ownerId:string;startAt:string;endAt:string};
export type Moderation={hidden:boolean;reason:string;actor:string;at:string};
export type GrowthBook={draftRev:number;rules:GrowthRule[];ledger:{key:string;ruleId:string;personId:string;amountOre:number;at:string}[];moderation:Record<string,Moderation[]>};
export function emptyGrowth():GrowthBook{return {draftRev:1,rules:[],ledger:[],moderation:{}};}
export function newGrowthRule(id:string,zone:string):GrowthRule{return {id,version:1,kind:"promo",zone,budgetOre:100000,rewardOre:5000,cap:1,targetTrips:8,stacks:false,enabled:true,ownerId:"",startAt:"",endAt:""};}
export function validateGrowth(r:GrowthRule):string|undefined{if(!r.id.trim()||!r.zone||!["promo","bonus","referral"].includes(r.kind))return "Choose an ID, kind and zone.";if([r.budgetOre,r.rewardOre,r.cap,r.targetTrips].some(v=>!Number.isSafeInteger(v)||v<=0)||r.rewardOre>r.budgetOre)return "Budgets, rewards, caps and targets must be positive whole numbers.";if(r.startAt&&!Number.isFinite(Date.parse(r.startAt)) || r.endAt&&(!Number.isFinite(Date.parse(r.endAt))||r.startAt&&Date.parse(r.endAt)<=Date.parse(r.startAt)))return "Invalid rule schedule.";}
export function saveGrowthRule(b:GrowthBook,r:GrowthRule):{book:GrowthBook;error?:string}{const error=validateGrowth(r);if(error)return {book:b,error};const spent=b.ledger.filter(x=>x.ruleId===r.id).reduce((n,x)=>n+x.amountOre,0);if(r.budgetOre<spent)return {book:b,error:"Budget cannot fall below committed rewards."};return {book:{...b,draftRev:b.draftRev+1,rules:[...b.rules.filter(x=>x.id!==r.id),{...r,version:(b.rules.find(x=>x.id===r.id)?.version??0)+1}]}};}
export function redeemGrowth(b:GrowthBook,id:string,person:DemoRecord,key:string,discounted=false,trips:readonly DemoRecord[]=[]):{book:GrowthBook;error?:string}{if(b.ledger.some(x=>x.key===key))return {book:b};const r=b.rules.find(x=>x.id===id);const fail=(error:string)=>({book:b,error});if(!r||!r.enabled)return fail("Rule is unavailable.");if(person.zoneId!==r.zone)return fail("Person is outside this rule's zone.");if(r.startAt&&Date.parse(r.startAt)>Date.now()||r.endAt&&Date.parse(r.endAt)<=Date.now())return fail("Rule is outside its schedule.");if(r.ownerId===person.id)return fail("Self-referral is not permitted.");if(discounted&&!r.stacks)return fail("This rule does not stack.");if(b.ledger.filter(x=>x.ruleId===id&&x.personId===person.id).length>=r.cap)return fail("Per-person cap reached.");if(r.kind==="bonus"&&trips.filter(t=>t.driverId===person.id&&t.status==="completed"&&t.zoneId===r.zone).length<r.targetTrips)return fail("Driver has not reached the trip target.");const spent=b.ledger.filter(x=>x.ruleId===id).reduce((n,x)=>n+x.amountOre,0);if(spent+r.rewardOre>r.budgetOre)return fail("Budget is exhausted.");return {book:{...b,draftRev:b.draftRev+1,ledger:[...b.ledger,{key,ruleId:id,personId:person.id,amountOre:r.rewardOre,at:new Date().toISOString()}]}};}
export function moderateGrowth(b:GrowthBook,id:string,hidden:boolean,reason:string,actor:string):{book:GrowthBook;error?:string}{if(!reason.trim())return {book:b,error:"A moderation reason is required."};return {book:{...b,draftRev:b.draftRev+1,moderation:{...b.moderation,[id]:[...(b.moderation[id]??[]),{hidden,reason,actor,at:new Date().toISOString()}]}}};}
export function growthReviews(trips:readonly DemoRecord[]){return trips.filter(t=>t.status==="completed").flatMap((t,i)=>[{id:`${t.id}-rider`,tripId:t.id,zone:t.zoneId,direction:"rider → driver",stars:i%2?4:5,text:"Simulated rider review"},{id:`${t.id}-driver`,tripId:t.id,zone:t.zoneId,direction:"driver → rider",stars:i%2?5:4,text:"Simulated driver review"}]);}
