import {test} from "node:test";import assert from "node:assert/strict";
import {createFixtureAdminApi,type CommandInput} from "./create.ts";
import {emptySafety,safetyAction,type SafetyBook} from "../safety/ops.ts";
import {emptySupport,supportChange,type SupportBook} from "../support/ops.ts";
import {emptyCampaigns,newCampaign,changeCampaign,type CampaignBook} from "../messages/ops.ts";
import {emptyStudio,studioSlot,changeStudio,type StudioBook} from "../content/studio.ts";
import {emptyGrowth,newGrowthRule,saveGrowthRule,type GrowthBook} from "../growth/ops.ts";
import {emptyReports,reportExport,type ReportsBook} from "../reports/ops.ts";
const all={zones:"all" as const,market:"SE-STO" as const};
test("R12–R17 authoritative simulation commands preserve identity permissions retries and persistence",async()=>{
 const api=createFixtureAdminApi(0);await api.reset();
 async function command(action:string,targetId:string,sliceKey:string,value:unknown,extra:Partial<CommandInput>={}){return api.command({action,targetId,sliceKey,value,actorId:"nora",actorRole:"super",actorScope:all,reason:"Acceptance",before:"",after:"saved",idempotencyKey:crypto.randomUUID(),expectedRev:await api.revision(),...extra});}
 const incident=(await api.list("incidents",null))[0];const take=safetyAction(emptySafety(),incident,"nora","take","accepted");const retry="incident-once";await command("admin.safety.take",incident.id,"safetyOps",take.book,{idempotencyKey:retry});await command("admin.safety.take",incident.id,"safetyOps",take.book,{idempotencyKey:retry});assert.equal((await api.readSlice<SafetyBook>("safetyOps",emptySafety())).incidents[incident.id].events.length,1);
 const tickets=await api.list("tickets",null);const replied=supportChange(emptySupport(),tickets[0],"nora","reply","Hello","line-one");await command("admin.support.reply",tickets[0].id,"supportOps",replied.book);const note=supportChange(await api.readSlice<SupportBook>("supportOps",emptySupport()),tickets[1],"nora","note","private","note-one");await command("admin.support.note",tickets[1].id,"supportOps",note.book);const persisted=await createFixtureAdminApi(0).readSlice<SupportBook>("supportOps",emptySupport());assert.equal(persisted.tickets[tickets[0].id].messages[0].text,"Hello");assert.equal(persisted.tickets[tickets[1].id].messages[0].delivery,"private");await assert.rejects(api.readSlice("supportOps",emptySupport(),{actorId:"anna",role:"viewer",scope:all}));
 const c={...newCampaign("campaign",incident.zoneId),sv:"Hej",en:"Hello"};await command("admin.campaign.save",c.id,"campaignOps",changeCampaign(emptyCampaigns(),c,"save","nora").book);const cb=await api.readSlice<CampaignBook>("campaignOps",emptyCampaigns());await command("admin.campaign.publish",c.id,"campaignOps",changeCampaign(cb,c,"publish","nora").book);assert.equal((await api.readSlice<CampaignBook>("campaignOps",emptyCampaigns())).campaigns[0].status,"published");
 const d={...studioSlot(emptyStudio(),"help").draft,sv:"Hej",en:"Help"};await command("admin.studio.save","help","studioOps",changeStudio(emptyStudio(),"help",d,"save","nora").book);const sb=await api.readSlice<StudioBook>("studioOps",emptyStudio());await assert.rejects(command("admin.studio.publish","help","studioOps",sb));await command("admin.studio.publish","help","studioOps",sb,{actorId:"otto",actorRole:"config"});assert.equal((await api.readSlice<StudioBook>("studioOps",emptyStudio())).slots.help.published?.en,"Help");
 const rule=newGrowthRule("promo",incident.zoneId);await command("admin.growthOps.save",rule.id,"growthOps",saveGrowthRule(emptyGrowth(),rule).book);assert.equal((await api.readSlice<GrowthBook>("growthOps",emptyGrowth())).rules[0].id,"promo");
 const filter={from:"2026-01-01",to:"2026-12-31",zone:incident.zoneId,status:""};const report=reportExport(emptyReports(),await api.list("trips",null),filter,"nora","export-one");await command("admin.report.export","trip-report","reportOps",report.book);assert.ok((await api.readSlice<ReportsBook>("reportOps",emptyReports())).jobs[0].csv.includes("Trip,Stockholm date"));await assert.rejects(command("admin.report.export","trip-report","reportOps",report.book,{actorId:"scoped",actorScope:{...all,zones:["Z002"]}}));
});
