export type CommandSpec = {
  id: string;
  label: string;
  reason: boolean;
  permission: string;
};

export type ActionScope = "global" | "zone" | "record";

export type ActionSpec = CommandSpec & {
  owner: string;
  entity: string;
  scope: ActionScope;
  destructive: boolean;
  idempotent: boolean;
  versioned: boolean;
  audit: "always" | "none";
  allowedStates?: readonly string[];
  approvalThresholdOre?: number;
};

const RAW_COMMANDS: CommandSpec[] = [
  { id: "admin.shell.menu", label: "Open menu", reason: false, permission: "overview.read" },
  { id: "admin.shell.search", label: "Search", reason: false, permission: "overview.read" },
  { id: "admin.shell.inbox", label: "Inbox", reason: false, permission: "overview.read" },
  { id: "admin.shell.reset", label: "Reset demo", reason: true, permission: "system.read" },
  { id: "admin.shell.signOut", label: "Sign out", reason: false, permission: "overview.read" },
  { id: "admin.shell.openHit", label: "Open search result", reason: false, permission: "overview.read" },
  { id: "admin.shell.closeSearch", label: "Close search", reason: false, permission: "overview.read" },
  { id: "admin.auth.signIn", label: "Sign in", reason: false, permission: "overview.read" },
  { id: "admin.auth.pickAgent", label: "Pick demo agent", reason: false, permission: "overview.read" },
  { id: "admin.audit.refund50", label: "Refund 50 kr", reason: true, permission: "payments.refund" },
  { id: "admin.audit.refund250", label: "Refund 250 kr", reason: true, permission: "payments.refund" },
  { id: "admin.config.save", label: "Save configuration draft", reason: false, permission: "settings.edit" },
  { id: "admin.config.publish", label: "Publish configuration", reason: true, permission: "settings.publish" },
  { id: "admin.config.approve", label: "Approve configuration", reason: true, permission: "settings.publish" },
  { id: "admin.config.review", label: "Send configuration for approval", reason: true, permission: "settings.edit" },
  { id: "admin.config.rollback", label: "Roll back configuration", reason: true, permission: "settings.publish" },
  { id: "admin.content.slot", label: "Choose content slot", reason: false, permission: "settings.read" },
  { id: "admin.content.publish", label: "Publish content", reason: true, permission: "settings.publish" },
  { id: "admin.content.rollback", label: "Roll back content", reason: true, permission: "settings.publish" },
  { id: "admin.design.drawer", label: "Open drawer", reason: false, permission: "system.read" },
  { id: "admin.design.confirm", label: "Open confirm", reason: false, permission: "system.read" },
  { id: "admin.design.action", label: "Sample action", reason: false, permission: "system.read" },
  { id: "admin.design.loading", label: "Show loading", reason: false, permission: "system.read" },
  { id: "admin.design.error", label: "Show error", reason: false, permission: "system.read" },
  { id: "admin.driver.activate", label: "Activate driver", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.review", label: "Review document", reason: true, permission: "documents.approve" },
  { id: "admin.driver.approveAll", label: "Approve remaining documents", reason: true, permission: "documents.approve" },
  { id: "admin.driver.requestInfo", label: "Request driver information", reason: true, permission: "documents.approve" },
  { id: "admin.driver.onHold", label: "Put driver on hold", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.suspend", label: "Suspend driver", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.reactivate", label: "Reactivate driver", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.bankReview", label: "Review driver bank details", reason: true, permission: "documents.approve" },
  { id: "admin.driver.note", label: "Save private driver note", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.category", label: "Change driver category eligibility", reason: true, permission: "drivers.activate" },
  { id: "admin.driverOps.save", label: "Save driver operations data", reason: true, permission: "documents.approve" },
  { id: "admin.vehicle.update", label: "Update vehicle compliance", reason: true, permission: "vehicles.edit" },
  { id: "admin.vehicle.hold", label: "Put vehicle on hold", reason: true, permission: "vehicles.edit" },
  { id: "admin.vehicle.activate", label: "Return vehicle to service", reason: true, permission: "vehicles.edit" },
  { id: "admin.vehicle.link", label: "Link vehicle to driver", reason: true, permission: "vehicles.edit" },
  { id: "admin.vehicle.reviewRegistration", label: "Review vehicle registration", reason: true, permission: "documents.approve" },
  { id: "admin.growth.redeem", label: "Redeem referral", reason: false, permission: "settings.read" },
  { id: "admin.growth.hide", label: "Hide review", reason: true, permission: "settings.read" },
  { id: "admin.handover.drills", label: "Run drills", reason: false, permission: "overview.read" },
  { id: "admin.message.useText", label: "Use template text", reason: false, permission: "settings.read" },
  { id: "admin.message.testSend", label: "Test send", reason: false, permission: "settings.read" },
  { id: "admin.message.mark", label: "Mark delivery", reason: false, permission: "settings.read" },
  { id: "admin.payment.markPaid", label: "Mark payout paid", reason: true, permission: "finance.read" },
  { id: "admin.payment.refund", label: "Refund payment", reason: true, permission: "payments.refund" },
  { id: "admin.payment.approveBank", label: "Approve bank details", reason: true, permission: "finance.read" },
  { id: "admin.payment.rejectBank", label: "Reject bank details", reason: true, permission: "finance.read" },
  { id: "admin.payment.savePolicy", label: "Save payment-method policy", reason: true, permission: "finance.read" },
  { id: "admin.payment.issueVoucher", label: "Issue wallet voucher", reason: true, permission: "finance.read" },
  { id: "admin.payment.voidVoucher", label: "Void wallet voucher", reason: true, permission: "finance.read" },
  { id: "admin.payment.reconcile", label: "Run reconciliation", reason: true, permission: "finance.read" },
  { id: "admin.approval.approve", label: "Approve pending action", reason: true, permission: "approval.decide" },
  { id: "admin.approval.reject", label: "Reject pending action", reason: true, permission: "approval.decide" },
  { id: "admin.pricing.saveAll", label: "Save all pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveZone", label: "Save price set", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.addCategory", label: "Add category", reason: false, permission: "settings.read" },
  { id: "admin.pricing.export", label: "Export rates", reason: false, permission: "settings.read" },
  { id: "admin.pricing.saveRow", label: "Save rate row", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.deleteRow", label: "Delete rate row", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveBooking", label: "Save booking controls", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveSurge", label: "Save surge", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.clearSurge", label: "Clear surge", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.activateBoost", label: "Activate boost", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveBoost", label: "Save boost", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.enableAuto", label: "Enable auto pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveAuto", label: "Save auto pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.schedule", label: "Schedule pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveSchedule", label: "Save schedule", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.removeSchedule", label: "Remove pricing schedule", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.restore", label: "Restore pricing version", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveRules", label: "Save pricing rules", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyOne", label: "Apply preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyTwo", label: "Apply second preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyThree", label: "Apply third preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.cancelCategory", label: "Cancel new category", reason: false, permission: "settings.read" },
  { id: "admin.pricing.createCategory", label: "Create category", reason: true, permission: "settings.publish" },
  { id: "admin.reservation.assign", label: "Assign reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.offer", label: "Offer reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.unassign", label: "Unassign reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.contact", label: "Log reservation contact", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.return", label: "Change return ride", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.savePolicy", label: "Save reservation policy", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.cancel", label: "Cancel reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.safetyOps.save", label: "Save safety policy", reason: true, permission: "safety.edit" },
  { id: "admin.safety.contact", label: "Log contact attempt", reason: true, permission: "safety.edit" },
  { id: "admin.safety.take", label: "Take incident", reason: true, permission: "safety.edit" },
  { id: "admin.safety.resolve", label: "Resolve incident", reason: true, permission: "safety.edit" },
  { id: "admin.support.assign", label: "Assign support ticket", reason: true, permission: "support.reply" },
  { id: "admin.support.draft", label: "Save private draft", reason: false, permission: "support.reply" },
  { id: "admin.support.metadata", label: "Update ticket metadata", reason: true, permission: "support.reply" },
  { id: "admin.supportOps.save", label: "Save support workspace", reason: true, permission: "support.reply" },
  { id: "admin.support.claim", label: "Claim ticket", reason: false, permission: "support.reply" },
  { id: "admin.support.reply", label: "Reply to rider", reason: true, permission: "support.reply" },
  { id: "admin.support.note", label: "Private note", reason: true, permission: "support.reply" },
  { id: "admin.team.invite", label: "Invite agent", reason: true, permission: "team.edit" },
  { id: "admin.team.editRole", label: "Change agent role", reason: true, permission: "team.edit" },
  { id: "admin.team.resetCode", label: "Reset 2-step code", reason: true, permission: "team.edit" },
  { id: "admin.team.deactivate", label: "Deactivate agent", reason: true, permission: "team.edit" },
  { id: "admin.team.reactivate", label: "Reactivate agent", reason: true, permission: "team.edit" },
  { id: "admin.team.presence", label: "Change agent presence", reason: false, permission: "team.edit" },
  { id: "admin.driver.revealSensitive", label: "Reveal driver sensitive data", reason: true, permission: "drivers.viewSensitive" },
  { id: "admin.rider.revealSensitive", label: "Reveal rider sensitive data", reason: true, permission: "riders.viewSensitive" },
  { id: "admin.trip.cancel", label: "Cancel trip", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.adjust", label: "Adjust fare", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.waiting", label: "Change waiting time", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.offer", label: "Offer to driver", reason: true, permission: "trips.intervene" },
  { id: "admin.rider.block", label: "Block rider", reason: true, permission: "riders.block" },
  { id: "admin.rider.unblock", label: "Unblock rider", reason: true, permission: "riders.block" },
  { id: "admin.rider.signOut", label: "Sign rider out", reason: true, permission: "riders.block" },
  { id: "admin.rider.credit", label: "Credit wallet", reason: true, permission: "finance.read" },
  { id: "admin.rider.privacy", label: "Advance privacy request", reason: true, permission: "riders.block" },
  { id: "admin.rider.note", label: "Save private rider note", reason: true, permission: "support.reply" },
  { id: "admin.rider.promoAdd", label: "Add rider promotion", reason: true, permission: "riders.promotions" },
  { id: "admin.rider.promoRemove", label: "Remove rider promotion", reason: true, permission: "riders.promotions" },
  { id: "admin.zone.publish", label: "Publish zones", reason: true, permission: "zones.publish" },
  { id: "admin.zone.review", label: "Send zones for review", reason: true, permission: "zones.edit" },
  { id: "admin.zone.rollback", label: "Roll back zones", reason: true, permission: "zones.publish" },
  { id: "admin.zone.create", label: "Create zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.drawPolygon", label: "Draw polygon", reason: false, permission: "zones.edit" },
  { id: "admin.zone.drawRectangle", label: "Draw rectangle", reason: false, permission: "zones.edit" },
  { id: "admin.zone.drawPoint", label: "Place pickup point", reason: false, permission: "zones.edit" },
  { id: "admin.zone.clear", label: "Clear drawing", reason: false, permission: "zones.edit" },
  { id: "admin.zone.cancel", label: "Cancel zone dialog", reason: false, permission: "zones.edit" },
  { id: "admin.zone.save", label: "Save zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.drawCircle", label: "Draw circle", reason: false, permission: "zones.edit" },
  { id: "admin.zone.drawFreehand", label: "Draw freehand", reason: false, permission: "zones.edit" },
  { id: "admin.zone.rotate", label: "Rotate zone", reason: false, permission: "zones.edit" },
  { id: "admin.zone.split", label: "Split zone", reason: false, permission: "zones.edit" },
  { id: "admin.zone.merge", label: "Merge zones", reason: false, permission: "zones.edit" },
  { id: "admin.zone.priority", label: "Reorder overlap priority", reason: false, permission: "zones.edit" },
  { id: "admin.zone.importKml", label: "Import KML", reason: false, permission: "zones.edit" },
  { id: "admin.zone.copyQueue", label: "Use shape as airport queue", reason: false, permission: "zones.edit" },
  { id: "admin.zone.copyPickupArea", label: "Use shape as airport pickup area", reason: false, permission: "zones.edit" },
  { id: "admin.zone.editPoints", label: "Edit points", reason: false, permission: "zones.edit" },
  { id: "admin.zone.cutHole", label: "Cut hole", reason: false, permission: "zones.edit" },
  { id: "admin.zone.undo", label: "Undo zone edit", reason: false, permission: "zones.edit" },
  { id: "admin.zone.redo", label: "Redo zone edit", reason: false, permission: "zones.edit" },
  { id: "admin.zone.export", label: "Export GeoJSON", reason: false, permission: "zones.read" },
  { id: "admin.zone.import", label: "Import GeoJSON", reason: false, permission: "zones.edit" },
  { id: "admin.zone.search", label: "Search address", reason: false, permission: "zones.read" },
  { id: "admin.zone.archive", label: "Archive zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.addPickup", label: "Add pickup point", reason: false, permission: "zones.edit" },
  { id: "admin.zone.restoreVersion", label: "Restore zone version", reason: true, permission: "zones.edit" },
  { id: "admin.table.retry", label: "Retry table", reason: false, permission: "overview.read" },
  { id: "admin.table.filter", label: "Add table filter", reason: false, permission: "overview.read" },
  { id: "admin.table.clearFilter", label: "Clear table filter", reason: false, permission: "overview.read" },
  { id: "admin.table.sort", label: "Sort table", reason: false, permission: "overview.read" },
  { id: "admin.table.menu", label: "Open row menu", reason: false, permission: "overview.read" },
  { id: "admin.table.open", label: "Open row", reason: false, permission: "overview.read" },
  { id: "admin.table.previous", label: "Previous page", reason: false, permission: "overview.read" },
  { id: "admin.table.next", label: "Next page", reason: false, permission: "overview.read" },
  { id: "admin.card.action", label: "Card action", reason: false, permission: "overview.read" },
  { id: "admin.thread.send", label: "Send message", reason: true, permission: "support.reply" },
  { id: "admin.modal.close", label: "Close dialog", reason: false, permission: "overview.read" },
  { id: "admin.tabs.select", label: "Select tab", reason: false, permission: "overview.read" },
  { id: "admin.ui.retry", label: "Retry", reason: false, permission: "overview.read" },
  { id: "admin.ui.configEdit", label: "Edit configuration draft locally", reason: false, permission: "settings.edit" },
  { id: "admin.ui.drawerClose", label: "Close drawer", reason: false, permission: "overview.read" },
  { id: "admin.doc.image", label: "Show license image", reason: false, permission: "system.read" },
  { id: "admin.doc.pdf", label: "Show license PDF", reason: false, permission: "system.read" },
  { id: "admin.doc.zoomIn", label: "Zoom in", reason: false, permission: "system.read" },
  { id: "admin.doc.zoomOut", label: "Zoom out", reason: false, permission: "system.read" },
  { id: "admin.doc.rotate", label: "Rotate document", reason: false, permission: "system.read" },
  { id: "admin.confirm.submit", label: "Confirm action", reason: false, permission: "overview.read" },
  { id: "admin.confirm.cancel", label: "Cancel dialog", reason: false, permission: "overview.read" },
  { id: "admin.trip.reassign", label: "Reassign trip", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.refund", label: "Refund trip", reason: true, permission: "payments.refund" },
  { id: "admin.dispatch.save", label: "Save dispatch rules", reason: true, permission: "trips.intervene" },
  { id: "admin.dispatch.restore", label: "Restore dispatch version", reason: true, permission: "trips.intervene" },
  { id: "admin.live.focus", label: "Focus live marker", reason: false, permission: "trips.read" },
];


const OWNER_BY_DOMAIN: Record<string, string> = {
  shell: "Platform",
  auth: "Platform",
  audit: "Finance",
  config: "Configuration",
  content: "Content",
  design: "Platform",
  driver: "Driver operations",
  driverOps: "Driver operations",
  vehicle: "Fleet operations",
  growth: "Growth",
  handover: "Operations",
  message: "Communications",
  payment: "Finance",
  approval: "Finance",
  pricing: "Pricing",
  reservation: "Dispatch",
  safety: "Safety",
  support: "Support",
  team: "Platform",
  trip: "Dispatch",
  rider: "Rider operations",
  zone: "Places",
  table: "Platform",
  card: "Platform",
  thread: "Support",
  modal: "Platform",
  tabs: "Platform",
  ui: "Platform",
  doc: "Compliance",
  confirm: "Platform",
  dispatch: "Dispatch",
  live: "Dispatch",
};

const ALLOWED_STATES: Record<string, readonly string[]> = {
  "admin.safety.take": ["queued"],
  "admin.safety.contact": ["taken"],
  "admin.safety.resolve": ["taken"],
  "admin.trip.cancel": ["searching", "accepted", "arrived", "in_trip"],
  "admin.trip.offer": ["requested", "searching"],
  "admin.trip.reassign": ["accepted", "driver_to_pickup", "arrived"],
  "admin.trip.adjust": ["accepted", "driver_to_pickup", "arrived", "rider_onboard", "in_trip", "approaching_dropoff"],
  "admin.trip.waiting": ["arrived", "rider_onboard", "in_trip"],
  "admin.trip.refund": ["completed", "cancelled_by_rider", "cancelled_by_driver", "cancelled_by_admin", "no_show", "failed"],
  "admin.driver.activate": ["pending", "on_hold"],
  "admin.driver.onHold": ["pending", "active"],
  "admin.driver.suspend": ["active", "on_hold"],
  "admin.driver.reactivate": ["suspended", "on_hold"],
  "admin.vehicle.hold": ["eligible", "ineligible"],
  "admin.vehicle.activate": ["on_hold", "ineligible"],
  "admin.reservation.assign": ["waiting", "booked"],
  "admin.reservation.offer": ["waiting", "booked"],
  "admin.reservation.unassign": ["assigned"],
  "admin.reservation.contact": ["waiting", "booked", "assigned"],
  "admin.reservation.return": ["waiting", "booked", "assigned"],
  "admin.reservation.cancel": ["waiting", "booked", "assigned"],
};

const DESTRUCTIVE = new Set([
  "admin.shell.reset",
  "admin.config.publish",
  "admin.config.rollback",
  "admin.content.publish",
  "admin.content.rollback",
  "admin.payment.refund",
  "admin.payment.rejectBank",
  "admin.payment.voidVoucher",
  "admin.approval.reject",
  "admin.pricing.deleteRow",
  "admin.pricing.removeSchedule",
  "admin.pricing.restore",
  "admin.reservation.cancel",
  "admin.safety.resolve",
  "admin.team.deactivate",
  "admin.driver.onHold",
  "admin.driver.suspend",
  "admin.vehicle.hold",
  "admin.trip.cancel",
  "admin.trip.refund",
  "admin.dispatch.restore",
  "admin.rider.block",
  "admin.rider.promoRemove",
  "admin.rider.privacy",
  "admin.zone.publish",
  "admin.zone.rollback",
  "admin.zone.archive",
]);

const GLOBAL_DOMAINS = new Set(["shell", "auth", "design", "handover", "table", "card", "modal", "tabs", "ui", "doc", "confirm"]);
const ZONE_DOMAINS = new Set(["zone", "config", "pricing", "dispatch", "live"]);

function scopeFor(domain: string): ActionScope {
  if (GLOBAL_DOMAINS.has(domain)) return "global";
  if (ZONE_DOMAINS.has(domain)) return "zone";
  return "record";
}

function enrich(command: CommandSpec): ActionSpec {
  const domain = command.id.split(".")[1] ?? "platform";
  return {
    ...command,
    owner: OWNER_BY_DOMAIN[domain] ?? "Platform",
    entity: domain,
    scope: scopeFor(domain),
    destructive: DESTRUCTIVE.has(command.id),
    idempotent: true,
    versioned: !GLOBAL_DOMAINS.has(domain),
    audit: GLOBAL_DOMAINS.has(domain) ? "none" : "always",
    allowedStates: ALLOWED_STATES[command.id],
    approvalThresholdOre:
      command.id === "admin.payment.refund" || command.id === "admin.audit.refund250"
        ? 20_000
        : undefined,
  };
}

export const COMMANDS: ActionSpec[] = RAW_COMMANDS.map(enrich);

const BY_ID = new Map(COMMANDS.map((command) => [command.id, command]));

export function commandById(id: string): ActionSpec | undefined {
  return BY_ID.get(id);
}
