export type CommandSpec = {
  id: string;
  label: string;
  reason: boolean;
  permission: string;
};

export const COMMANDS: CommandSpec[] = [
  { id: "admin.shell.menu", label: "Open menu", reason: false, permission: "overview.read" },
  { id: "admin.shell.search", label: "Search", reason: false, permission: "overview.read" },
  { id: "admin.shell.inbox", label: "Inbox", reason: false, permission: "overview.read" },
  { id: "admin.shell.reset", label: "Reset demo", reason: true, permission: "system.read" },
  { id: "admin.shell.signOut", label: "Sign out", reason: false, permission: "overview.read" },
  { id: "admin.shell.openHit", label: "Open search result", reason: false, permission: "overview.read" },
  { id: "admin.shell.closeSearch", label: "Close search", reason: false, permission: "overview.read" },
  { id: "admin.auth.signIn", label: "Sign in", reason: false, permission: "overview.read" },
  { id: "admin.auth.pickAgent", label: "Pick demo agent", reason: false, permission: "overview.read" },
  { id: "admin.audit.refund50", label: "Refund 50 kr", reason: true, permission: "finance.refund" },
  { id: "admin.audit.refund250", label: "Refund 250 kr", reason: true, permission: "finance.refund" },
  { id: "admin.config.publish", label: "Publish configuration", reason: true, permission: "settings.publish" },
  { id: "admin.config.approve", label: "Approve configuration", reason: true, permission: "settings.publish" },
  { id: "admin.config.review", label: "Send configuration for approval", reason: true, permission: "settings.edit" },
  { id: "admin.config.rollback", label: "Roll back configuration", reason: true, permission: "settings.publish" },
  { id: "admin.content.slot", label: "Choose content slot", reason: false, permission: "settings.read" },
  { id: "admin.content.publish", label: "Publish content", reason: true, permission: "settings.publish" },
  { id: "admin.content.rollback", label: "Roll back content", reason: true, permission: "settings.publish" },
  { id: "admin.design.drawer", label: "Open drawer", reason: false, permission: "system.read" },
  { id: "admin.design.confirm", label: "Open confirm", reason: false, permission: "system.read" },
  { id: "admin.design.action", label: "Sample action", reason: false, permission: "system.read" },
  { id: "admin.design.loading", label: "Show loading", reason: false, permission: "system.read" },
  { id: "admin.design.error", label: "Show error", reason: false, permission: "system.read" },
  { id: "admin.driver.activate", label: "Activate driver", reason: true, permission: "drivers.activate" },
  { id: "admin.driver.review", label: "Review document", reason: true, permission: "documents.approve" },
  { id: "admin.driver.approveAll", label: "Approve remaining documents", reason: true, permission: "documents.approve" },
  { id: "admin.growth.redeem", label: "Redeem referral", reason: false, permission: "settings.read" },
  { id: "admin.growth.hide", label: "Hide review", reason: true, permission: "settings.read" },
  { id: "admin.handover.drills", label: "Run drills", reason: false, permission: "overview.read" },
  { id: "admin.message.useText", label: "Use template text", reason: false, permission: "settings.read" },
  { id: "admin.message.testSend", label: "Test send", reason: false, permission: "settings.read" },
  { id: "admin.message.mark", label: "Mark delivery", reason: false, permission: "settings.read" },
  { id: "admin.payment.markPaid", label: "Mark payout paid", reason: true, permission: "finance.read" },
  { id: "admin.payment.approveBank", label: "Approve bank details", reason: true, permission: "finance.read" },
  { id: "admin.pricing.saveAll", label: "Save all pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveZone", label: "Save price set", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.addCategory", label: "Add category", reason: false, permission: "settings.read" },
  { id: "admin.pricing.export", label: "Export rates", reason: false, permission: "settings.read" },
  { id: "admin.pricing.saveRow", label: "Save rate row", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.deleteRow", label: "Delete rate row", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveBooking", label: "Save booking controls", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveSurge", label: "Save surge", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.clearSurge", label: "Clear surge", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.activateBoost", label: "Activate boost", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveBoost", label: "Save boost", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.enableAuto", label: "Enable auto pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveAuto", label: "Save auto pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.schedule", label: "Schedule pricing", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveSchedule", label: "Save schedule", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.saveRules", label: "Save pricing rules", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyOne", label: "Apply preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyTwo", label: "Apply second preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.applyThree", label: "Apply third preset", reason: true, permission: "settings.publish" },
  { id: "admin.pricing.cancelCategory", label: "Cancel new category", reason: false, permission: "settings.read" },
  { id: "admin.pricing.createCategory", label: "Create category", reason: true, permission: "settings.publish" },
  { id: "admin.reservation.assign", label: "Assign reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.reservation.cancel", label: "Cancel reservation", reason: true, permission: "trips.intervene" },
  { id: "admin.safety.take", label: "Take incident", reason: true, permission: "safety.edit" },
  { id: "admin.safety.resolve", label: "Resolve incident", reason: true, permission: "safety.edit" },
  { id: "admin.support.claim", label: "Claim ticket", reason: false, permission: "support.reply" },
  { id: "admin.support.reply", label: "Reply to rider", reason: true, permission: "support.reply" },
  { id: "admin.support.note", label: "Private note", reason: true, permission: "support.reply" },
  { id: "admin.team.deactivate", label: "Deactivate agent", reason: true, permission: "team.read" },
  { id: "admin.trip.cancel", label: "Cancel trip", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.adjust", label: "Adjust fare", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.offer", label: "Offer to driver", reason: true, permission: "trips.intervene" },
  { id: "admin.rider.block", label: "Block rider", reason: true, permission: "riders.block" },
  { id: "admin.rider.signOut", label: "Sign rider out", reason: true, permission: "riders.block" },
  { id: "admin.rider.credit", label: "Credit wallet", reason: true, permission: "finance.read" },
  { id: "admin.rider.privacy", label: "Advance privacy request", reason: true, permission: "riders.block" },
  { id: "admin.zone.publish", label: "Publish zones", reason: true, permission: "zones.publish" },
  { id: "admin.zone.review", label: "Send zones for review", reason: true, permission: "zones.edit" },
  { id: "admin.zone.rollback", label: "Roll back zones", reason: true, permission: "zones.publish" },
  { id: "admin.zone.create", label: "Create zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.drawPolygon", label: "Draw polygon", reason: false, permission: "zones.edit" },
  { id: "admin.zone.drawRectangle", label: "Draw rectangle", reason: false, permission: "zones.edit" },
  { id: "admin.zone.drawPoint", label: "Place pickup point", reason: false, permission: "zones.edit" },
  { id: "admin.zone.clear", label: "Clear drawing", reason: false, permission: "zones.edit" },
  { id: "admin.zone.cancel", label: "Cancel zone dialog", reason: false, permission: "zones.edit" },
  { id: "admin.zone.save", label: "Save zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.drawCircle", label: "Draw circle", reason: false, permission: "zones.edit" },
  { id: "admin.zone.editPoints", label: "Edit points", reason: false, permission: "zones.edit" },
  { id: "admin.zone.cutHole", label: "Cut hole", reason: false, permission: "zones.edit" },
  { id: "admin.zone.undo", label: "Undo zone edit", reason: false, permission: "zones.edit" },
  { id: "admin.zone.redo", label: "Redo zone edit", reason: false, permission: "zones.edit" },
  { id: "admin.zone.export", label: "Export GeoJSON", reason: false, permission: "zones.read" },
  { id: "admin.zone.import", label: "Import GeoJSON", reason: false, permission: "zones.edit" },
  { id: "admin.zone.search", label: "Search address", reason: false, permission: "zones.read" },
  { id: "admin.zone.archive", label: "Archive zone", reason: true, permission: "zones.edit" },
  { id: "admin.zone.addPickup", label: "Add pickup point", reason: false, permission: "zones.edit" },
  { id: "admin.zone.restoreVersion", label: "Restore zone version", reason: true, permission: "zones.edit" },
  { id: "admin.table.retry", label: "Retry table", reason: false, permission: "overview.read" },
  { id: "admin.table.filter", label: "Add table filter", reason: false, permission: "overview.read" },
  { id: "admin.table.clearFilter", label: "Clear table filter", reason: false, permission: "overview.read" },
  { id: "admin.table.sort", label: "Sort table", reason: false, permission: "overview.read" },
  { id: "admin.table.menu", label: "Open row menu", reason: false, permission: "overview.read" },
  { id: "admin.table.open", label: "Open row", reason: false, permission: "overview.read" },
  { id: "admin.table.previous", label: "Previous page", reason: false, permission: "overview.read" },
  { id: "admin.table.next", label: "Next page", reason: false, permission: "overview.read" },
  { id: "admin.card.action", label: "Card action", reason: false, permission: "overview.read" },
  { id: "admin.thread.send", label: "Send message", reason: true, permission: "support.reply" },
  { id: "admin.modal.close", label: "Close dialog", reason: false, permission: "overview.read" },
  { id: "admin.tabs.select", label: "Select tab", reason: false, permission: "overview.read" },
  { id: "admin.ui.retry", label: "Retry", reason: false, permission: "overview.read" },
  { id: "admin.ui.drawerClose", label: "Close drawer", reason: false, permission: "overview.read" },
  { id: "admin.doc.image", label: "Show license image", reason: false, permission: "system.read" },
  { id: "admin.doc.pdf", label: "Show license PDF", reason: false, permission: "system.read" },
  { id: "admin.doc.zoomIn", label: "Zoom in", reason: false, permission: "system.read" },
  { id: "admin.doc.zoomOut", label: "Zoom out", reason: false, permission: "system.read" },
  { id: "admin.doc.rotate", label: "Rotate document", reason: false, permission: "system.read" },
  { id: "admin.confirm.submit", label: "Confirm action", reason: false, permission: "overview.read" },
  { id: "admin.confirm.cancel", label: "Cancel dialog", reason: false, permission: "overview.read" },
  { id: "admin.trip.reassign", label: "Reassign trip", reason: true, permission: "trips.intervene" },
  { id: "admin.trip.refund", label: "Refund trip", reason: true, permission: "payments.refund" },
  { id: "admin.dispatch.save", label: "Save dispatch rules", reason: true, permission: "trips.intervene" },
  { id: "admin.live.focus", label: "Focus live marker", reason: false, permission: "trips.read" },
];

const BY_ID = new Map(COMMANDS.map((command) => [command.id, command]));

export function commandById(id: string): CommandSpec | undefined {
  return BY_ID.get(id);
}
