export type OpenValue = { id: string; label: string; today: string };

/** Unconfirmed product defaults. Today's value is the demo default. Do not invent a second number. */
export const OPEN_VALUES: OpenValue[] = [
  { id: "offer-time", label: "Offer time", today: "8.5 s" },
  { id: "search-radius", label: "Search radius", today: "30 km" },
  { id: "next-trip", label: "Next-trip radius", today: "30 km" },
  { id: "free-waiting", label: "Free waiting", today: "2 min" },
  { id: "waiting-fee", label: "Waiting fee", today: "none" },
  { id: "no-show", label: "No-show time", today: "5 min" },
  { id: "no-show-fee", label: "No-show fee", today: "none" },
  { id: "stop-waiting", label: "Stop waiting fee", today: "none" },
  { id: "prices", label: "Prices", today: "rider sample prices" },
  { id: "adjustment", label: "Adjustment range", today: "65–180%" },
  { id: "cancel-fee", label: "Cancellation fee", today: "none published" },
  { id: "free-cancel", label: "Free-cancel window", today: "2 minutes after accept" },
  { id: "horizon", label: "Reservation horizon", today: "7 days" },
  { id: "lead", label: "Assignment lead", today: "30 min" },
  { id: "give-up", label: "Give-up time", today: "5 min" },
  { id: "tips", label: "Tips", today: "10/20/30 kr" },
  { id: "commission", label: "Commission", today: "none" },
  { id: "documents", label: "Required documents", today: "11 listed" },
  { id: "driving-hours", label: "Driving hours", today: "none" },
  { id: "payments", label: "Payment methods", today: "8 in app" },
  { id: "cash", label: "Cash rules", today: "open" },
  { id: "fleet", label: "Fleet partners at launch", today: "open" },
  { id: "thresholds", label: "Money approval thresholds", today: "open" },
  { id: "refund", label: "Refund second person", today: "200 kr" },
  { id: "wallet-ceiling", label: "Wallet credit ceiling", today: "500 kr" },
  { id: "languages", label: "Languages", today: "Swedish and English" },
  { id: "app-languages", label: "App languages today", today: "English only" },
  { id: "vehicles", label: "Vehicle requirements", today: "none" },
  { id: "taxi", label: "Swedish taxi compliance", today: "open" },
  { id: "quote", label: "Quote validity", today: "2 minutes" },
  { id: "reservation-wait", label: "Included reservation waiting", today: "5 minutes" },
  { id: "topup", label: "Wallet top-up", today: "100, 200, 500 kr" },
  { id: "travel", label: "Impossible travel", today: "55 m/s" },
  { id: "stops", label: "Max stops", today: "3" },
  { id: "contacts", label: "Trusted contacts", today: "5" },
  { id: "window", label: "Acceptance window", today: "last 100 requests" },
  { id: "sticky", label: "Support sticky owner", today: "3 days" },
  { id: "idle", label: "Idle sign-out", today: "15 minutes" },
  { id: "code", label: "Session code", today: "6 digits, labelled demo" },
  { id: "maps", label: "Google Maps key", today: "empty" },
];
