import { useState } from "react";
import { useParams } from "react-router";
import { emptySupport, supportChange, ticketOps, useRecords, useSlice, type SupportBook } from "../api/hooks";
import { AGENTS, can, canUseZone } from "../auth/permissions";
import { useSession } from "../auth/SessionContext";
import { CommandButton } from "./CommandButton";
export function SupportWorkspace({chat=false}:{chat?:boolean}) {
 const {agent}=useSession(); const {id}=useParams(); const rows=useRecords("tickets"); const store=useSlice<SupportBook>("supportOps",emptySupport()); const [selected,setSelected]=useState(id??""); const [thread,setThread]=useState("rider"); const [query,setQuery]=useState(""); const [draft,setDraft]=useState<Record<string,string>>({}); const [owner,setOwner]=useState(""); const [attachment,setAttachment]=useState(""); const [notice,setNotice]=useState("");
 const list=(rows.data??[]).filter((r,i)=>(!chat || (thread==="rider" ? i%2===0:i%2===1)) && `${r.id} ${r.name}`.toLowerCase().includes(query.toLowerCase()));
 const row=list.find(r=>r.id===selected)??list[0]; const ops=row?ticketOps(store.value,row):null; const key=`${agent?.id}:${row?.id}`; const text=draft[key]??store.value.drafts[key]??""; const eligible=AGENTS.filter(a=>a.active && can(a.role,"support.reply") && row && canUseZone(a,row.zoneId)); const chosen=owner||eligible[0]?.id||"";
 function prepared(kind:Parameters<typeof supportChange>[3]) { return row ? supportChange(store.value,row,agent?.id??"",kind,text,crypto.randomUUID(),chosen,attachment) : {book:store.value,error:"Choose a ticket."}; }
 return <><div className="page-heading"><div><h2>{chat?"Chat":"Support"}</h2><p>Scoped ticket queue, 3-day ownership and isolated Rider/Driver threads. Replies are simulated; attachment names are metadata only.</p></div></div><p role="status">{notice}</p>{rows.error?<p role="alert">{rows.error.message}</p>:null}
 {chat?<div className="actions">{["rider","driver"].map(t=><button type="button" key={t} data-command="admin.tabs.select" className="secondary-btn" onClick={()=>{setThread(t);setSelected("");setAttachment("");}}>{t==="rider"?"Rider thread":"Driver thread"}</button>)}</div>:null}
 <label>Search tickets<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Ticket<select value={row?.id??""} onChange={e=>{setSelected(e.target.value);setAttachment("");setOwner("");}}>{list.map(r=><option key={r.id} value={r.id}>{r.id} · {r.name} · {r.status}</option>)}</select></label>
 {row && ops?<article className="panel"><h3>{row.id} · {row.name}</h3><p>Owner {ops.owner??"Unassigned"} {ops.ownerUntil?`until ${ops.ownerUntil}`:""} · SLA {ops.dueAt} · {ops.priority} · {ops.language}</p>
 <div className="actions"><CommandButton command="admin.support.claim" targetId={row.id} scope={row.zoneId} sliceKey="supportOps" expectedSliceRev={store.value.draftRev} value={prepared("claim").book} disabled={store.loading} onDone={()=>setNotice("Claimed for 3 days.")}>Claim</CommandButton><label>Assign agent<select value={chosen} onChange={e=>setOwner(e.target.value)}>{eligible.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><CommandButton command="admin.support.assign" targetId={row.id} scope={row.zoneId} sliceKey="supportOps" value={prepared("assign").book} expectedSliceRev={store.value.draftRev} confirmTarget={false} disabled={!chosen || store.loading}>Assign</CommandButton></div>
 <div className="actions">{["normal","urgent"].map(priority=><CommandButton key={priority} command="admin.support.metadata" targetId={row.id} scope={row.zoneId} sliceKey="supportOps" value={supportChange(store.value,row,agent?.id??"","metadata","","",undefined,undefined,{priority:priority as "normal"|"urgent"}).book} expectedSliceRev={store.value.draftRev} confirmTarget={false}>Priority {priority}</CommandButton>)}</div>
 <ul aria-label="Ticket messages">{ops.messages.map(m=><li key={m.id}>{m.actor}: {m.text} · {m.kind==="note"?"Private note":m.delivery}{m.attachment?` · Attachment metadata: ${m.attachment}`:""}</li>)}</ul>
 <label>Message<textarea aria-label="Message" value={text} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label><label>Attachment name (metadata only)<input value={attachment} onChange={e=>setAttachment(e.target.value)}/></label>
 <button type="button" data-command="admin.message.useText" className="secondary-btn" onClick={()=>setDraft({...draft,[key]:ops.language==="sv"?"Vi undersöker ditt ärende.":"We are reviewing your request."})}>Use response macro</button>
 <div className="actions">{(["reply","note","draft"] as const).map(kind=>{const result=prepared(kind);return <CommandButton key={kind} command={`admin.support.${kind}`} targetId={row.id} scope={row.zoneId} sliceKey="supportOps" expectedSliceRev={store.value.draftRev} value={result.book} confirmTarget={false} disabled={store.loading||Boolean(result.error)} title={result.error} onDone={()=>{if(kind!=="draft")setDraft({...draft,[key]:""});setNotice(kind==="reply"?"Reply saved once to this simulated thread.":kind==="note"?"Private note saved. It is not sent to the app.":"Draft saved.");}}>{kind==="reply"?"Send reply":kind==="note"?"Private note":"Save draft"}</CommandButton>;})}</div></article>:<p>{rows.isLoading?"Loading tickets…":"No tickets in this scope."}</p>}</>;
}
